INSERT INTO CLIENTE(ID, NOME, DATA_CADASTRO, STATUS) VALUES('1', 'Renato Alves', '2020-08-12', 'ATIVO');
INSERT INTO CLIENTE(ID, NOME, DATA_CADASTRO, STATUS) VALUES('2', 'Fulano de Tal', '2020-08-13', 'INATIVO');

INSERT INTO PRODUTO(ID, NOME, VALOR, DISPONIVEL) VALUES('1', 'Caixa de Som', 800, true);

INSERT INTO PEDIDO(ID, DATA_CADASTRO, STATUS, ID_CLIENTE) VALUES('1', '2020-08-12', 'ENTREGUE', '1');

INSERT INTO PRODUTO_PEDIDO(ID_PEDIDO, ID_PRODUTO, QUANTIDADE) VALUES('1', '1',2);

